### ISSUE TITLE
[팀프로젝트] 24.11.05 회의

### ISSUE THREAD

**Issue by sw2park** [sw2park/Ticatch#4]
# 24.11.05 회의 내용
## 1. 24.11.08까지(기간 관련 추가 의논 가능)
1. 조 이름, 프로젝트 명 생각해오기
2. 타겟사이트(서울문화포털, 인터파크, 티켓링크 등) 기능 조사하기

## 2. 위 내용 진행 후
- 구현할 기능 정리
- 포지션(프론트, 백) 어떻게 할지 의논 필요
- DB 설계

**Comment by dkim0910** [comment]
6일

**Comment by dkim0910** [comment]
11

**Comment by kybxdc** [comment]
test1

**Comment by dkim0910** [comment]
조 이름 : 섭종하조
프로젝트명 : 티켓다이스 (티켓 + 파라다이스 합성어) 읽을땐 티겟 다있쓰 (티켓 다있어)
타겟사이트 : 
 - 서울문화 포털 - 이건 근데 예매가 아닌 예매로 가는 웹페이지 링크들이 있는 사이트임
 - 인터파크 티켓 : 예매 사이트 
(공연 및 뮤지컬 등) 예매 가능한 웹사이트 만들기 예매할때 날짜랑 좌석 위치까지 잘 나와있음 단 로그인 후에 예매 가능함.
티켓링크 : 예매 사이트
인터파크랑 디자인만 다르지 기능은 비슷함 

너무 기능이 많음 - 정리좀 하면 로그인, 회원가입, 카테고리별로 정리된 예매 방식, 예매, 후기, 장바구니, 출연진 및 감독 정보. 후기 등 (감상전 평, 찜, 지도로 공연 장소 표시 등)

개발 하고 싶은것들 :  예매, 예매하면 자동으로 나의 캘린더에 위치랑 시간 (선택한 좌석있음 죄석까지) 저장됨
(지금은 공연 예매만)
예매 :
 - 로그인 후에 가능함.

 ![Image](https://github.com/user-attachments/assets/422da73c-4105-47da-81ba-b3193876e0f7)
이건 티켓링크 

![Image](https://github.com/user-attachments/assets/9ef7b98b-286f-4808-a52f-348b361bb29b)
이건 인터파크

- 아래에 감독 및 출연진 정보 , 후기 등 더 있기는 함 (공연 정보는 상세 정보 같은거)

 - 구매하는것이 공연, 스포츠 관람 이면 좌석선택이 있고 전시회 같은건 그냥 바로 구매가능 

@ 홈페이지 -> 원하는 공연 선택 -> 공연 페이지 여기서 날짜 선택 후 -> 예매 버튼  클릭시 로그인 하라고 팝업 -> 예매 페이지에서 좌석 지정있으면 좌석 선택 및 인원 선택 (날짜는 앞에서 가지고온걸로)(여기서도 바꿀 수 있게 만들기) -> 날짜, 인원수, 좌석 선택했으면 구매 클릭 -> 구매 버튼 클릭시 지정해놓은 달력에 자동적으로 시간, 공연 위치, 좌석 등이 저장됨.  (마지막은 시간 있으면 하기)

 예매 하고 싶은 사람 있으면 회원 리뷰 페이지랑 공연 페이지에 들어갈 만한 리뷰 만들기
5점 만점 노란색 별 5개로 로그인 되어있는지 확인 후 별 선택하고 짧게 후기 작성하고 나중에 마이페이지? 같은거도 있으면 회원이 작성한 후기만 볼 수 있어도 좋을 듯

**Comment by sonhongseok** [comment]
조 이름 : 다나오조
프로젝트명 : ticketbox(티켓박스)

타겟사이트 : 인터파크, 멜론티켓, 타임티켓

# 기능
### 상세페이지 장소 지도
![image](https://github.com/user-attachments/assets/d59e7c76-830c-4fc9-8435-0f9cfdeda1fe)
 - 상세페이지에서 장소를 클릭하면 공연 및 전시회 위치 장소가 나옴

(기능은 더 조사할 예정)

**Comment by namomin** [comment]
### 조이름
개발왕조

### 프로젝트 이름
아트리움

### 인터파크 기능 정리
![사이트맵1](https://github.com/user-attachments/assets/e4113fac-20d2-455f-a47e-b341789f69a0)
![사이트맵2](https://github.com/user-attachments/assets/523130f3-c478-4fb6-b3fa-6d23661a343b)

**Comment by syc0708** [comment]
### 조 이름
1찍끝내조

### 프로젝트 명 
티캐치 = (ticket + catch)

### 타겟 사이트 
인터파크 , 티켓링크

### 기능 구현
- 메인페이지
 
- 로그인 ,회원가입 ,마이페이지

- 캘린더

- 예매
 
- 정보 조회

- 예매 랭킹 순 (시간 남으면 ..)

- 후기

**Comment by sw2park** [comment]
# 24.11.08 회의 정리
## 조 이름
- 다나오조

## 프로젝트 명
- 티캐치 ticatch (ticket + catch)

## 타겟사이트
- 메인 : 서울문화포털
- 서브 : 인터파크, 티켓링크

## 각 타겟 사이트 별 기능
### 메인 : 서울문화포털
- 기본적으로 서울에서 진행되는 공연, 전시회 정보만 제공하기 때문에 예매 기능이 없다.
- 문화포털 API 제공으로 데이터 가져올 수 있다.

### 서브 1 : 인터파크
- 상세 정보 페이지
![Image](https://github.com/user-attachments/assets/9ef7b98b-286f-4808-a52f-348b361bb29b)
- 기능 리스트
![사이트맵1](https://github.com/user-attachments/assets/e4113fac-20d2-455f-a47e-b341789f69a0)
![사이트맵2](https://github.com/user-attachments/assets/523130f3-c478-4fb6-b3fa-6d23661a343b)

### 서브 2 : 티켓링크
 ![Image](https://github.com/user-attachments/assets/422da73c-4105-47da-81ba-b3193876e0f7)

기능|서울문화포털|인터파크|티켓링크
-|-|-|-
API|제공|미제공|미제공
예매 및 결제|X|O|O
좌석 선택|X|O|O
리뷰|X|O|O
Q&A|X|O|O
로그인|O|O|O
네이버/구글/카카오|X|O|O

## 담당 포지션
1. 메인,로그인,회원가입, 헤더&푸터 : 손홍석, 신윤창
2. 상세페이지 : 이혜원
3. 마이페이지 : 박성우 
4. 예매 : 김민성

## 팀 운영 방식
손홍석, 신윤창 : 각각 한명씩 F/B 번갈아서 진행
김민성 : F/B 둘 다 진행
박성우 : F/B 둘 다 진행
이혜원 : F/B 둘 다 진행

**Comment by dkim0910** [comment]
손홍석, 신윤창 : 각각 한명씩 F/B 번갈아서 진행 / 회원가입 및 메인페이지 / 헤더 및 푸터 
와이어 프레임 
김민성 : 예매 / 플로우 차트
박성우 : API / DB / 마이페이지 / ERD
이혜원 : 상세페이지 / 플로우차트
